### ISSUE TITLE
Texture on ground 

### ISSUE THREAD

**Issue by daneshtarapore** [AranBSmith/MAP-Elites-Rhex#5]
Hi Aran,

Hope you are well. 

Can you please confirm if you were able to render any texture on the ground of the walking robot, so as to better visualize the distance it has covered?

Thanks,
Danesh.

**Comment by AranBSmith** [comment]
Hello!

There is a grid visual in DART framework: [example](https://github.com/dartsim/dart/blob/80fcc9f9d82bce563af554729f84f8926c45a14d/examples/point_cloud/main.cpp#L755-L762)

However this can't be done with the version of DART that this project is implemented with. This code would benefit from the use of updating the DART framework that it uses. 

I implemented a trajectory visualization which you could see when you run https://github.com/AranBSmith/rhex_simu. Handy for testing specific controllers.

[Here](https://github.com/AranBSmith/rhex_simu/blob/master/rhex_dart/include/rhex_dart/visualizations.hpp#L44-L86) is the implentation for the robot trajectory.  
[Here] is how to use the visualization. 

![Screenshot from 2019-11-23 15-39-07](https://user-images.githubusercontent.com/16102369/69481234-6dec8b00-0e07-11ea-8a87-98b6cbc8c08d.png)

**Comment by daneshtarapore** [comment]
Okay, thanks.
